"""empty message

Revision ID: 49f43259bbb9
Revises: 61ed3d049ca4
Create Date: 2022-11-15 14:10:22.469670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f43259bbb9'
down_revision = '61ed3d049ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_verwendung', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.drop_column('in_verwendung')

    # ### end Alembic commands ###
