"""set zugkraft, sitzanzahl and gewicht nullable

Revision ID: 61ed3d049ca4
Revises: 5ac24e8b4612
Create Date: 2022-11-11 10:25:17.630057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ed3d049ca4'
down_revision = '5ac24e8b4612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.alter_column('max_zugkraft',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sitzanzahl',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gewicht',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.alter_column('gewicht',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sitzanzahl',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_zugkraft',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
