"""empty message

Revision ID: 7060c9bc92e9
Revises: 92410bba56b0
Create Date: 2022-11-15 17:44:03.393149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7060c9bc92e9'
down_revision = '92410bba56b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zug', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_waggons_fg_nummer'), ['fg_nummer'])
        batch_op.create_foreign_key(batch_op.f('fk_waggons_zug_zuege'), 'zuege', ['zug'], ['id'])

    with op.batch_alter_table('zuege', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_zuege_nummer'), ['nummer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zuege', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_zuege_nummer'), type_='unique')

    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_waggons_zug_zuege'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_waggons_fg_nummer'), type_='unique')
        batch_op.drop_column('zug')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    # ### end Alembic commands ###
