"""adding model Waggons, Triebwagen and Personenwaggon.

Revision ID: 9c9dfb72a1b1
Revises: 
Create Date: 2022-11-11 09:56:55.598253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9dfb72a1b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waggons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fg_nummer', sa.String(length=120), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('max_zugkraft', sa.Integer(), nullable=False),
    sa.Column('sitzanzahl', sa.Integer(), nullable=False),
    sa.Column('gewicht', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fg_nummer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waggons')
    # ### end Alembic commands ###
