"""empty message

Revision ID: dced9a511c58
Revises: 49f43259bbb9
Create Date: 2022-11-15 14:21:43.223864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dced9a511c58'
down_revision = '49f43259bbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_verwendung', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.drop_column('in_verwendung')

    # ### end Alembic commands ###
