"""empty message

Revision ID: 207da8bed468
Revises: 314c9e21a836
Create Date: 2022-11-15 17:31:53.685000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207da8bed468'
down_revision = '314c9e21a836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zuege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nummer', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nummer')
    )
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zug', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'zuege', ['zug'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('zug')

    op.drop_table('zuege')
    # ### end Alembic commands ###
