"""empty message

Revision ID: 314c9e21a836
Revises: dced9a511c58
Create Date: 2022-11-15 14:29:06.694910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314c9e21a836'
down_revision = 'dced9a511c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.alter_column('in_verwendung',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waggons', schema=None) as batch_op:
        batch_op.alter_column('in_verwendung',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
