"""empty message

Revision ID: 509df5a66818
Revises: 7060c9bc92e9
Create Date: 2022-11-15 17:45:51.399860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509df5a66818'
down_revision = '7060c9bc92e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zuege', schema=None) as batch_op:
        batch_op.drop_constraint('uq_zuege_nummer', type_='unique')
        batch_op.drop_column('nummer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zuege', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nummer', sa.VARCHAR(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_zuege_nummer', ['nummer'])

    # ### end Alembic commands ###
