"""make zugkraft, sitzanzahl and gewicht nullable

Revision ID: 5ac24e8b4612
Revises: 9c9dfb72a1b1
Create Date: 2022-11-11 10:04:05.259999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac24e8b4612'
down_revision = '9c9dfb72a1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waggons', 'max_zugkraft',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waggons', 'sitzanzahl',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waggons', 'gewicht',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waggons', 'gewicht',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waggons', 'sitzanzahl',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waggons', 'max_zugkraft',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
