"""empty message

Revision ID: a8b20e3faeb1
Revises: 509df5a66818
Create Date: 2022-11-15 17:46:47.199452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b20e3faeb1'
down_revision = '509df5a66818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zuege', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nummer', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_zuege_nummer'), ['nummer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zuege', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_zuege_nummer'), type_='unique')
        batch_op.drop_column('nummer')

    # ### end Alembic commands ###
